# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

###############################################################################################
# example: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
###############################################################################################

# The `service` block is the name of the service
service: serverless-test

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: python3.7
  stage: dev
  profile: zzqadmin
  region: us-east-1
  timeout: 30
  apiGateway:
    restApiId: qw9ix93pt6
    restApiRootResourceId: rb95ljhya8
  environment:
    MY_STAGE: dev
    AUTHOR: zzq

# The `functions` block defines what code to deploy
functions:
  echo:
    name: python_lambda_echo
    description: 测试lambda-echo
    handler: echo.lambda_handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /echo
          method: post
          cors: true
  test:
    name: python_lambda_test
    description: 测试lambda-test
    handler: test.lambda_handler
    events:
      - http:
          path: /test
          method: post
          cors: true